### ISSUE TITLE
VApp properties are ignored when VM customization is performed

### ISSUE THREAD

**Issue by omniproc** [pulumi/pulumi-vsphere#144] opened 2020-10-24 15:13 UTC
In `pulumi-vsphere 2.9.0 `vapp properties are passed into the vm correctly but the post ova deployment vm customization doesnt work (cpu, memory, disk will be whatever was defined in the ova itself).
In `pulumi-vsphere 2.10.0` and higher the post ova deployment vm customization works properly, but now vapp properties are missing after the deployment.

Example minimal ova for testing: https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_vmware_ova.ova

Example code:
```
import pulumi
import pulumi_vsphere as vsphere

dc = vsphere.get_datacenter(name="dcname")
cl = vsphere.get_compute_cluster(name="clstname", datacenter_id=dc.id)
ds = vsphere.get_datastore(name="diskname", datacenter_id=dc.id)
nw = vsphere.get_network(name="network", datacenter_id=dc.id)
hs = vsphere.get_host(name="hostname", datacenter_id=dc.id)
vm = vsphere.VirtualMachine("pulumi01",
datacenter_id=dc.id,
datastore_id=ds.id, 
host_system_id=hs.id,
resource_pool_id=cl.resource_pool_id,
wait_for_guest_net_timeout=0,
wait_for_guest_ip_timeout=0,
disks=[vsphere.VirtualMachineDiskArgs(label="disk0", size=10, thin_provisioned=False)],
num_cpus=4,
memory=2048,
ovf_deploy=vsphere.VirtualMachineOvfDeployArgs(
  local_ovf_path = "/path/to/flatcar_production_vmware_ova.ova",
  ovf_network_map = {
      "VM Network": nw.id
    }
),
vapp=vsphere.VirtualMachineVappArgs(
  properties={
    "guestinfo.hostname":"pulumi01",
    "guestinfo.ignition.config.data.encoding": "base64",
    "guestinfo.ignition.config.data": "something"
  }
)
)
```

**Comment by omniproc** [comment] 2021-02-01 13:20
Probably fixed in https://github.com/hashicorp/terraform-provider-vsphere/pull/1322/commits 
Needs testing

**Comment by lethargosapatheia** [comment] 2023-06-30 21:53
Is this dependent on terraform strictly? On terraform I can confirm this works ina ny case, but I have to add that I'm not using guestinfo for vapp, but directly 'user-data' and 'hostname', so there might be a mistake on the part of the OP. For example:
```
  vapp {
    properties = {
        user-data = base64encode(data.template_cloudinit_config.kubernetes["${each.key}"].rendered)
        "hostname" = "${each.key}"
    }
  }
```

**Comment by mikhailshilkov** [comment] 2023-08-09 21:16
Since the upstream issue was fixed, I'm resolving this one too

**Closed by mikhailshilkov** 2023-08-09 21:16 UTC
Labels: kind/bug, awaiting-upstream, resolution/fixed
